Chinese Translation
Mithion/Mana-And-Artifice pull request #725
Opened 2024-03-10 16:59 UTC by xiaoknya

Updated to the newest version of mna
(based on the translated version on https://www.mcmod.cn/class/2773.html by"清秋"and"QQ酱740777")

2024-03-28 12:09 UTC, Mithion commented
This is marked as ready for review but is still receiving patches.  Please mark as draft until it is completely ready to be reviewed.  I don't want to include it until it's ready.  If it is in fact ready now, please comment and let me know.  Thanks!

2024-03-28 12:59 UTC, xiaoknya commented
> This is marked as ready for review but is still receiving patches.  Please mark as draft until it is completely ready to be reviewed.  I don't want to include it until it's ready.  If it is in fact ready now, please comment and let me know.  Thanks!

So sorry for the late response! It's all prepared and ready for review now, thank you!

2024-03-29 15:36 UTC, TUsama requested changes
part one

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +        "value": "织魔者村民",
为何要多加村民二字？

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "，其中包含瓶装魔纹，可用于快速使用，还有"
我没记错的我原来的译文是魔织，为何这里改动了？

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +        "value": "符文工匠会售卖一些刻印口袋、标记符文以及其他可用于符文刻印和构装体合成的物品。织魔者的工作方块为符文刻印桌。",
统一性。

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "进行交易以换取包含这些花的"
```suggestion
进行交易，以换取包含这些花的
```

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "我已经创造了魔法合成常见的普通材料的方法，这些材料往往是稀有或难以获得的，但却经常用于魔法。\n\n我相信随着我的进阶，我会想出更多方法。我会确保在这里列出它们。"
```suggestion
某些魔法材料平素稀有难见或是昂贵无比，偏偏又会经常用到。所以我研究出了一种能够使用魔法将凡俗材料合成为这类材料的方法，解我燃眉之急。\n\n随着我的升阶，我肯定还能开发出更多的合成方法，介时我会将这些新增方法列在此处。
```
机翻味太浓。

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "的造物。\n\n为了对抗其他派系的飞行威胁而被创造的“活化守卫”是一种小型的飞行构装体，魔法抗性很高。他们发射的闪电会减少目标的魔力，并小幅度降低目标的魔力回复速度。\n\n当处于危险中时，它们可以自爆以大幅度降低大范围目标的魔力回复速度。"
恢复

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "的兵种之一。 \n\n他们远比看起来要更身形敏捷，并可以从近处和远处发动强大的毒素攻击，然而他们近距离的毒素攻击要危险得多。"
不通顺，建议修改。

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "的爪牙之一。\n\n这些球的飞行速度会越来越慢，但所造成的伤害却会不断上升，被球锁定的人只能左支右绌的进行闪躲，最后精疲力竭。这些球会收割掉被击中者的生命力，而且据说还会吸取魔力。"
我上次翻源码，发现这里其实指的是，这个球会令被击中者减速，并且被击中者的减速等级越高，所造成的伤害就越高。你帮我修改一下。

2024-03-29 15:36 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "派系的兵种之一。\n\n这种令人惊惧的追猎者可以施放出烟雾弹遮掩自身。它们对于放冷箭的技术了如指掌，能够对敌人造成大量的伤害。它们还能掷出高速而致命的手里剑进行攻击，而对于飞在空中的敌人，它们则会掷出一把大刀，尝试将敌人打回至地面上。"
我一直很疑惑这里的bolos是什么，在lang中，好像骷髅刺客丢出来的是手里剑（shuriken）。

2024-03-29 15:38 UTC, TUsama commented
@Mithion Unsubscribe this PR is recommended cuz it may explode your e-mail in the next few days :)

2024-03-29 15:39 UTC, xiaoknya commented
> @Mithion Unsubscribe this PR is recommended cuz it may explode your e-mail in the next few days :)

感谢，我已经将PR设为draft方便修改。

2024-03-29 15:59 UTC, Mithion commented
Don't forget this exists too:
https://manaandartifice.com/codex-editor/#/

2024-03-29 16:04 UTC, xiaoknya commented
> Don't forget this exists too: https://manaandartifice.com/codex-editor/#/

Thanks! This could be a huge help with changing text colors :)

2024-03-29 16:06 UTC, xiaoknya commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "派系的兵种之一。\n\n这种令人惊惧的追猎者可以施放出烟雾弹遮掩自身。它们对于放冷箭的技术了如指掌，能够对敌人造成大量的伤害。它们还能掷出高速而致命的手里剑进行攻击，而对于飞在空中的敌人，它们则会掷出一把大刀，尝试将敌人打回至地面上。"
抱歉，这些已有的文本我之前没有进行纠正 :( Part1部分我已按意见修改。
"Bolos"这个词在不同语境中有不同的含义，但在许多情况下，特别是在描述武器时，它指的是一种有两个或多个重物连接在一根绳子或链条两端的投掷武器。即我们常见的套索。详见https://en.wikipedia.org/wiki/Bolas

2024-03-30 14:33 UTC, TUsama requested changes
后面缺了很多。我之前测试的时候，手册应该是读取json数组内的内容，之前的value好像是直接弃用了。然后从我的最后一条review起，后面好像是很多条目内都没有json数组。我不确定能不能正常读取，你可以测试一下。
你可以加群920229087，这样方便联系。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +      }
漏掉了大段的文本，看一下原文。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "对于巫师而言，使用法杖、魔杖或手镯施法，才能体现出巫师的尊贵优雅。法杖和魔杖的外观非常精美，并且当我只是想要将法术握在手中时手镯非常合适"
本段中的换行符丢失了。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "。"
该段需要完全重写。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "提升持续时间、提升法术距离或提升施法速度",
此处的三个附魔译名不太符合一般的习惯，应该将“提升”后置，从动宾结构转换为主谓结构。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "将使法术的持续时间、法术距离或释放速度分别获得与附魔等级相对应的提升。\n\n"
“施放”法术，“进行”仪式，这是我在译本中约定俗成的。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "附魔效果,赋予施法者以下效果，每一个效果都按照力量附魔的等级来获得提升:\n\n灰烬和弹射物法术获得自动索敌能力。\n\n印记的单次放置数量及上限提高。\n\n坠击的坠落伤害加成提高。"
需修改。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "附魔效果,赋予施法者一个脉冲伤害光环，在跳跃时潜行将会化为雾形态，可以短时间拥有爆发性的飞行能力"
标点。

2024-03-30 14:33 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +      },
格式不正确，参照原文。

2024-03-30 15:31 UTC, xiaoknya commented on src/main/resources/assets/mna/guide/zh_cn.json
> +        "value": "喋喋不休者"
在我翻阅https://en.wikipedia.org/wiki/Chatterer后，发现在国内将其出现在《猛鬼追魂》中的原型Chatterer翻译为颤齿，你觉得这个译名怎么样？

2024-03-30 15:39 UTC, TUsama commented on src/main/resources/assets/mna/guide/zh_cn.json
> +        "value": "喋喋不休者"
@Mithion is this chatterer referring to the [Chatterer from the Hellraiser](https://en.wikipedia.org/wiki/Chatterer)?

2024-03-30 15:47 UTC, xiaoknya commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "魔力转送",
此处句点在1830行。

2024-03-30 15:51 UTC, xiaoknya commented on src/main/resources/assets/mna/guide/zh_cn.json
> +            "text": "附魔效果,赋予施法者以下效果，每一个效果都按照力量附魔的等级来获得提升:\n\n灰烬和弹射物法术获得自动索敌能力。\n\n印记的单次放置数量及上限提高。\n\n坠击的坠落伤害加成提高。\n\n当你在查阅奥秘之眼时，任何需要远古巫师议会派系作为要求的对象，都会带有如下的图标："
感谢，已按此修正guide和lang。

2024-03-30 16:19 UTC, xiaoknya commented on src/main/resources/assets/mna/guide/zh_cn.json
> +      },
仪式章节开始的还没有改过格式，待我在codex-editor中修改一会。

2024-03-30 16:22 UTC, xiaoknya commented
> 后面缺了很多。我之前测试的时候，手册应该是读取json数组内的内容，之前的value好像是直接弃用了。然后从我的最后一条review起，后面好像是很多条目内都没有json数组。我不确定能不能正常读取，你可以测试一下。 你可以加群920229087，这样方便联系。

我已经提交群申请，古籍是条目中没有json便读取value作为文本，正常使用还是可以的。仪式章节开始的都没有改过格式了，因为我之前还不知道有codex-editor的存在……改起来太麻烦了。

2024-04-09 03:23 UTC, TUsama approved these changes
@Mithion Hi Mithion, It's all done here, this PR is ready to be merged.

2024-04-17 14:47 UTC, merged